name: Evaluate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Hyperfine
        run: |
          brew install hyperfine

  eval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ 
          # './59', 
          './112', 
          # './113', 
          './145', 
          # './156'
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run eval
        run: |
          cd ${{ matrix.dir }}
          go build -o ${{ matrix.dir }}
          hyperfine --warmup 3 --min-runs 10 "./${{ matrix.dir }}"