name: Evaluate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.dir }}
    strategy:
      matrix:
        dir: [ 
          # './59', 
          './112', 
          # './113', 
          './145', 
          './156'
        ]
    timeout-minutes: 60
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build go executable
        run: go build -o ${{ matrix.dir }}

      - name: eval executable
        run: ${{ matrix.dir }}