name: Evaluate

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [ 
          # './59', 
          './112', 
          # './113', 
          './145', 
          './156'
        ]
    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run eval
        run: |
          cd ${{ matrix.dir }}
          go build -o ${{ matrix.dir }}
          ./${{ matrix.dir }}